### ISSUE TITLE
Motoru döndürmek yerine ekrana mesaj yazdırmasını istiyorum.

### ISSUE THREAD

**Issue by ozalpmurat** [sinnaydogan/Cizgi-izleyen-robot#5]
Motoru döndürene kadar arada birçok bileşen olduğundan, problemi tespit etmek zor oluyor. Bu nedenle motoru döndürme kısmını silmeden, aynı fonksiyonların içerisine ekrana mesaj yazdırma ekle. "Sağa dönüyor", "Sola sönüyor", "Düz gidiyor" gibi mesajlar yazsın ekranda.

**Comment by sinnaydogan** [comment]
Cmd ekranına  mesaj yazdırılması yapıldı ve güncel kod depoya eklendi.
